### ISSUE TITLE
Fails to highlight the syntax with record extensions

### ISSUE THREAD

**Issue by ggreco** [cross-language-cpp/vscode-djinni#1]
Example:

`
Team = record +c {
    id: i64;
    image: string;
    name: string;
    coach: string;
}
`

The **+c** breaks syntax highlighting.

A quick fix is replacing line 125:

`"begin": "(\\w+)\\s*(=)\\s*(record)\\s*({)",`

with

`"begin": "(\\w+)\\s*(=)\\s*(record)\\s+((\\+[cjo]\\s+)*)({)",`

... in **~/.vscode/extensions/patrikminder.djinni-syntax-highlighting-1.0.1/syntaxes/djinni.tmLanguage.json**

But an extension update would be better!

**Comment by Durza007** [comment]
Thank you for the report! I applied your fix and updated the extension.
