### ISSUE TITLE
Future development of vscode-djinni

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/vscode-djinni#2]
Hi Patrick
First if all, thank you for that plugin! I use and like it.

I wonder if you would be interested to move that repo to  https://github.com/cross-language-cpp/ , where we continue to develop djinni and tools/technologies around it as a community project. (You might know that dropbox/djinni is an abandoned project). See also the new documentation pages at https://djinni.xlcpp.dev/

You can of course still be the maintainer of this plugin, if you want.
It would be nice to have that plugin alongside the Intelli J djinni plugin, so it is easier to find and it can be developed / adopted with possible upcoming future changes/extensions to the djinni IDL.

We would be very happy if you could consider that as an option for the future of this plugin.

**Comment by Durza007** [comment]
Hi!
Yeah, that sounds good to me. I'm fine with someone else being the maintainer as well.

**Comment by a4z** [comment]
Hi Patrik, thanks for the positive feedback! 

We do for sure not want to put any additional burden on you. 
Once there is a repo is in  xlcpp, there will be no singe maintainer, but all of us will care. And contributions are on volunteer.

We want for sure acknowledge you with the work on that plugin.
And I would find it cool if you would at least make code reviews if there are ever changes on the plugin. But even that is on volunteer base.

I am not sure what the best way to transfer the repo is. 
There is a transfer method, this means we need to add you to https://github.com/cross-language-cpp/  because for doing a transfer you need permission to create repos there.
If you are ok with doing so,  we will add you to the org so you can do that.
https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

But I am unsure what this means for the VS Code plugin that is already on the marketplace, do you know if this would need any action ? I never been through the process of publishing a plugin on the marketplace.

**Comment by Durza007** [comment]
Yes, I can do the transfer method.

As for the publishing I just followed this guide: https://code.visualstudio.com/api/working-with-extensions/publishing-extension
The plugin is hosted in an organization named 'patrikminder'. It seems like it is possible to add members that can also publish aside from me.
But I feel like it might be better to simply resubmit the plugin under a different organization maintained by you guys?
I did find another plugin that had a similar issue and they referenced some relevant issues over on vscode: https://github.com/prettier/prettier-vscode/issues/41#issuecomment-313622390

**Comment by a4z** [comment]
Thanks for the thumbs up for the transfer Patrik!
I invited you to join https://github.com/cross-language-cpp/ , once you accept you should be able to create repos there, and therefore also do the transfer.

Also a big thank you for doing the research on how do deal with the vs code plugin! 
Doing a resubmit sounds like an option. We can add that as an extra issue.

**Comment by Durza007** [comment]
Great! I think the transfer is complete now.

**Comment by a4z** [comment]
Awesome Patrik! Thanks a lot!! 

Now it becomes serious to find out what that means for the plugin on the marketplace ...
@jothepro , any preferences ? 

I have skimmed over the docs, they talk from an azure organisation, but not sure if that is required.
I have already one since some time  https://dev.azure.com/xlcpp/ as a playground (there is the cmake djinni trail ;-) 

However, I think just one person should play that through and we should first agree on how to proceed with that.
@jothepro , would you like to do that . I wonder if that could be tied to a/the common email we have ,like the JetBrains plugin? 

or shall we continue using the existing org and ask Patrik to add us, and the upcoming CI/CD as members....

**Comment by jothepro** [comment]
I'd prefer to publish the plugin under a new account, as @Durza007 recommended.

I have created an issue on the new release process (including the need for a new publisher account): #3

**Comment by a4z** [comment]
Thanks Johannes! 

I just tested in VS Code, a click on the repo from the extension leads to this repo.
So this forward is working. 

I wonder if we should adopt the README of this repo , and ask Patrik to make one more release to the `patrikminder` publisher that has infos about the repo change...

**Comment by jothepro** [comment]
Hm. I'd also be fine with adding a note to the newly released plugin, that it is now the official plugin. And then just advertise it on the mobilecpp slack to make existing users move over.

**Comment by a4z** [comment]
We can handle that in the context of #3 , if this is ok for you, @Durza007.
You are of course more than welcome to participate if you want, for the plugin or any other component around djinni 

Since you did everything to resolve that issue, would you mind to close it, Patrik?
